### ISSUE TITLE
animated hands Displayed very slowly

### ISSUE THREAD

**Issue by kknsy** [Corysia/Unity-Oculus-Example#6]
After the project is running, the arm is not loaded immediately but it takes a while to load it. I don’t know if you have encountered it.

**Comment by Corysia** [comment]
"A while" for me is about 3-5 seconds.  I admit it's a bit jarring not to see your hands immediately, but it's out of my control.  The delay is due to the Quest going out and contacting Oculus servers and trying to load your avatar.

There are alternatives.  For instance, you could instead use a Hand asset and not use the Oculus hands at all.  You might decide to do full body presence and IK.  But these are out of scope for this example.

**Comment by kknsy** [comment]
Thank you, I just want to confirm if this problem exists.
